### ISSUE TITLE
create testbeds

### ISSUE THREAD

**Issue by cwulfman** [TrustTheVote-Project/NIST-1500-100-103-examples#19]
Requirements:

- ballot measure
- contest for office
   - 1 of x
   - n out of m
   - presidential (each ballot item is two people)

must have several precincts

Jetsons election model has 3 of the 4 objects; but it lacks a presidential contest.

EJS:
EDF 1 -- the Jetsons (no president)
EDF 2 -- adds presidential

March milestone: an EDF that is similar in structure to Jetsons, and include a presidential contest

**Comment by awoflaherty** [comment]
## Expanding on the tests.  
1. Test 1 very basic with Jetsons contests in NIST V1
2. Test 2 Includes 4 precinct with the first 2 as basic and 3 includes a long ballot measure and 4 includes a presidential election in ~NIST V1~ changed to NIST V2
3. Test 3 more real world data and in NIST V2

Details below
## EDF 1: NIST V1, the Jetsons
precinct 1:
2 @ 1 of x  contests
2 @ n out of m contests
1 @ ballot measure (very very short question)
0 @ presidential contests
///
## EDF 2: NIST ~V1~ V2, the Jetsons
precinct 1:
2 @ 1 of x  contests
2 @ n out of m contests
1 @ ballot measure (very very short question)
0 @ presidential contests
///
precinct 2:
2 @ 1 of x  contests
2 @ n out of m contests
1 @ ballot measure (very very short question)
0 @ presidential contests
///
precinct 3:
2 @ 1 of x  contests
2 @ n out of m contests
1 @ ballot measure (very long question)
0 @ presidential contests
///
precinct 4:
2 @ 1 of x  contests
2 @ n out of m contests
1 @ ballot measure (average question length)
1 @ presidential contests
///
## EDF 3: Same as EDF2, Replace text with more real world examples and in NIST V2

**Comment by awoflaherty** [comment]
I'd like EDF1 as soon as possible while the other can wait.  We need to add the filter precinct code to Elroy v2 first.

**Comment by mattbeattie** [comment]
Request: for the NIST v2 EDFs, can we get them in both XML and JSON format?

**Comment by awoflaherty** [comment]
Or do we want just json format?

**Comment by cwulfman** [comment]
John Dziurłaj's resources about the NIST standards is illuminating and well worth reviewing: https://github.com/HiltonRoscoe/CDFPrototype; https://github.com/HiltonRoscoe/CDFConverter. In fact, many of the tools and resources he has produced may be of use to us.

**Comment by trustthevote** [comment]
This EDF #1 looks fine in XML and may be the right one for an Elroy demo. Also please provide in properly converted JSON. If Bret's code is converting XML to JSON as a first step, my suggestion would be to use the JSON version, so the app can skip the translation step, which could introduce some errors.

**Comment by cwulfman** [comment]
HiltonRoscoe doesn't have a v1 xml->json converter, so I'm going to do this by hand.

**Comment by awoflaherty** [comment]
I have changed my request for EDF 2 from NIST v1 to NIST v2 so we can utilize HiltonRoscoe'v V2 xml->json converter

**Comment by cwulfman** [comment]
I have established a test_cases directory at the top of the repo: https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/tree/main/test_cases. It currently contains 2 files:
- https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/EDF_1.xml, for Bret; a very minimal version-1 definition of the basic Jetsons contest, for the Elroy demo
- https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/EDF_1.json, a test of a modified xml->json translation for Matt to review.

**Comment by awoflaherty** [comment]
Is EDF_1.json in NIST v1 or V2?

**Comment by cwulfman** [comment]
EDF_1.json is NIST 2.  Bret **should not** use it. There is no "valid" translation of v1 xml to json.  

**EDF_1.xml was created for Bret to use in the upcoming demo.**

**Comment by mattbeattie** [comment]
@cwulfman I took a look at `EDF_1.json` and had a few questions. Rather than inject them into this thread, I opened a new issue to discuss them here: https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/issues/29
