### ISSUE TITLE
What needs to be displayed for the "n-of-m" vote variation of the candidate contest? 

### ISSUE THREAD

**Issue by mattbeattie** [TrustTheVote-Project/NIST-1500-100-103-examples#23]
Question about what needs to be displayed for the "n-of-m" vote variation of the candidate contest:

https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/NIST_1500-100/version_2/n-of-m_contest.xml

When looking at the `Contest`, I see it lists the following information (and _only_ the following information):

```xml
<Contest xsi:type="CandidateContest" ObjectId="town_council_contest">
    <ElectionDistrictId>princeton_borough</ElectionDistrictId>
    <Name>For Princeton Town Council</Name>
    <VoteVariation>n-of-m</VoteVariation>
    <OfficeIds>princeton_councilmember_1 princeton_councilmember_2 princeton_councilmember_3
        princeton_councilmember_4 princeton_councilmember_5 princeton_councilmember_6
        princeton_councilmember_7</OfficeIds>
    <VotesAllowed>7</VotesAllowed>
</Contest>
```

While I can easily do a lookup to get the corresponding office information by these Office IDs, I'm not sure what should be displayed. Should the _offices_ be displayed on the screen? Or should the _candidates_ be displayed on the screen?

I do see that there are 13 Candidates (named `candidate_cnum_xx`); but they don't relate in any way to anything in the Contest. For example, I can search for `candidate_cnum_1` and only get the single reference to it in the list of Candidates. 

Is the UI supposed to allow the user to match candidate to office? Or just the candidates? How should all of this be displayed? Any guidance here would be most appreciated.

**Comment by cwulfman** [comment]
This example isn't complete (and shouldn't be in the main branch; sorry). I'm waiting on a response from John Sebes about how to represent this.  See f89a94ed172963fbf8150731784f5f65c2bd041b

**Comment by cwulfman** [comment]
https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/pull/28

**Comment by mattbeattie** [comment]
Excellent, thank you. I'll close this one and we can follow up on the PR you opened there. Looks like John has already replied.

Worth noting this is a good case where there may be multiple write-ins (for multiple seats), so that helps the other question I posed elsewhere.
