### ISSUE TITLE
Will there ever be a case where there will be more than one write-in per contest?

### ISSUE THREAD

**Issue by mattbeattie** [TrustTheVote-Project/NIST-1500-100-103-examples#26]

**Comment by cwulfman** [comment]
The schema allows for it: a CandidateContest can have more than one CandidateSelection, and a CandidateSelection may or may not be a writein. Whether more than one writein is allowed in practice would be a matter of election law, I think.

**Comment by trustthevote** [comment]
In any EDF that's normal for the real world, the number of write in slots is equal to the number of candidate choices the voter makes. For 1-of-X contests for, there would be one write in slot; for N-of-M contests, there would be N write in slots. In the special 1-of-X that is prez-vp, the one write in slot probably doesn't have the structure of two separate names but IRL a valid write-in would have to be a string like "Bugs Bunny and Daffy Duck" (it would be up to a ballot marker to enforce that). Whenever we construct EDFs, we should make them that way. Note that ballot questions (including judge retention contests) do not have write in. In some future EMS, there would be an option for the ballot designer to indicate for a contest in an EDF under construction, that that contest should have zero write in slots. (It's a rare corner case in some states).

**Comment by mattbeattie** [comment]
This is helpful, thank you both. Will close this one out, I appreciate the examples!
