### ISSUE TITLE
What system is in charge of validating EDFs/CVRs?

### ISSUE THREAD

**Issue by mattbeattie** [TrustTheVote-Project/NIST-1500-100-103-examples#27]
For our EDFs XML files, there are two kinds of validation:

1. Schema validation, which is relatively easy and can likely be solved with some library
2. "Completeness" validation, which is harder and requires some custom code

For the purpose of this topic, I'm referring to the second type of validation. Here are some examples:

* `Contest`'s `ContestSelection` candidate identifiers don't match any of the candidates
* `Contest`'s `ContestSelection` candidate identifiers matches more than one of the candidates
* Candidate's `partyID` isn't listed in the `Party` section

In those cases, the EDF is structurally accurate, but not logically complete. We're able to parse it, but we're unable to query internally to get all the data we need to display on the page.

Is this a solved problem in the election world? What system is in charge of doing this kind of validation?

**Comment by mattbeattie** [comment]
For now this must be solved within Elroy's parsing logic. That requires a nontrivial amount of defensive programming to handle all these potential failure cases. I'm not even sure what the desired behavior of the application would be - fail outright, display partial data, make some call to some external system announcing the failure?

Ideally, I think this EDF parsing should live in some API somewhere. That API would be responsible for sending Elroy _exactly_ what it needs, in a sensible data format which Elroy can take and simply display to the user. In the end state though, I'm not sure where that would fit.

**Comment by mattbeattie** [comment]
Similarly, what system ensures that Elroy is generating a structurally accurate and logically complete CVR? Astro? What validations does it need to do, what potential error cases must it handle, and what is the desired behavior in the application under those cases?

**Comment by cwulfman** [comment]
This sort of "buisness logic" is best handled with Schematron: https://en.wikipedia.org/wiki/Schematron

**Comment by trustthevote** [comment]
Well, technically it would be a bug in the system that produces an EDF to produce one with a semantic validation error like this. (Just like it would for omitted a required data element.) But Elroy data import should be robust against syntactically valid semantically erroneous EDFs. But how robust? Let's see as we go along. No need to think up every possible error. I'd suggest this rubric: if the error would make it hard/impossible to produce a semantically valid CVR, then the error is definitely worth checking for. Certainly an undefined candidate ID meets that rubric.

**Comment by mattbeattie** [comment]
Cool, I agree. How about this: we'll build error catching/handling into Elroy to account for these things as we see them. I have a few already, and we can leave them in. If/when we see more, we'll handle the error and add another check.

Cliff - I hadn't heard of Schematron, that's pretty cool. Would potentially be nice to handle that in some external system _before_ it gets to Elroy; however, I figure handling this in Elroy's parsing logic for now should be fine.

Will go ahead and close this one out since we've got a resolution - thank you both.
