### ISSUE TITLE
Questions about EDF_1.json

### ISSUE THREAD

**Issue by mattbeattie** [TrustTheVote-Project/NIST-1500-100-103-examples#29]
In reviewing the example NIST 2.0 EDF in JSON format, I have a few questions

https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/EDF_1.json

1. How do you map from `ContestSelection` to `Candidate`? I see that a subset of the strings match up, for example `candidate-cosmo-spacely` and `contest-mayor--selection-cosmo-spacely`; however, it's not a _exact_ match. Does this format require some fuzzy matching or string parsing in order to do this mapping?
2. We've previously confirmed that `ContestSelection`s can have multiple candidates (https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/issues/24). In this format though, each `ContestSelection` object has an `@id` property which is of type `string`. In this example though, none of these strings match anything else in the document. How is that one-to-many relationship accounted for here?
3. `ExternalIdentifier` jumped out at me here, though I now see it's also in some of the 2.0 EDF XML formats as well. I read in the spec that it's for associating a jurisdiction's codes. Do these have any material impact on how Elroy should display the ballots?
4. I see this includes a contest of vote variation `plurality`; however, we haven't discussed that vote variation before. I only account for `n-of-m`, `majority` and `presidential` based on the conversations we've had and the examples provided. Is `plurality` something we'll need to handle? If so, how should it be displayed?

**Comment by cwulfman** [comment]
Looks like the EDF file isn't complete. I'll look into this.

**Comment by mattbeattie** [comment]
Closing this issue as this EDF has been replaced by the two new examples. Thanks for providing those!
