### ISSUE TITLE
How should we display `OrderedContent`s that contain `OrderedHeader`s?

### ISSUE THREAD

**Issue by mattbeattie** [TrustTheVote-Project/NIST-1500-100-103-examples#35]
In the ballot markup application, we parse an EDF into a list of contests that is displayed to the voter. In order to derive the list of contests, we need to know what ballot style to use.

The `BallotStyle` class contains an array of `OrderedContent`s. The `OrderedContent` class is [defined as follows](https://pages.nist.gov/ElectionResultsReporting/#18_5_3_43701b0_1527684342715_643544_6146):

> OrderedContent is an abstract class with two subclasses that get used according to the type of content:
>
>*OrderedContest, used for the appearance of a contest. *OrderedHeader, used for the appearance of a header, optionally with the inclusion of contests.

Displaying the first subclass (`OrderedContest`) is straightforward, as it contains a reference to exactly one `Contest`. This is a nice 1-to-1 relationship, and the logic simply finds all the `Contests` and displays them to the voter.

Displaying the second subclass (`OrderedHeader`) is not as easy. My initial read of the documentation and the provided example gave me conflicting information, which leads me to my initial question.

### Possibility one: `OrderedHeader`s contain `OrderedContent`s

The documentation states that `OrderedHeader` class contains one or more `OrderedContent`s.

![image](https://user-images.githubusercontent.com/7593323/155038212-5462b272-f5f2-4de6-8738-93a80e49c5eb.png)

What I expected based on that information is to have a potentially infinitely nestable object, where the `OrderedHeader` can contain an `OrderedContent` that contains one or more `OrderedHeader`s that contain an `OrderedContent` that contains... you get the picture. 

This doesn't make sense to me, and I'm not sure how this would work in practice, or why the model would need to account for such a relationship. Is this potentially a bug in the documentation?

### Possibility two:  `OrderedHeader`s contain `OrderedContest`s

What I see in [example_2.json](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/example_2.json#L11-L23) is that the `OrderedHeader` actually contains one or more `OrderedContest`s. This makes more sense to me.

However, this means we have a "one-to-many" relationship here, where the `OrderedContent`'s `OrderedHeader`s have multiple `OrderedContest`s, each of which have exactly one `Contest`. Thus the possibility of the following exists:

```
OrderedHeader 1
  OrderedContest a
    Contest x
  OrderedContest b
    Contest y
OrderedHeader 2
  OrderedContest c
    Contest z
  OrderedContest d
    Contest q
```

In this case, do we simply display `Contest`s x, y, z, and q?

The following possibility _also_ exists, where we have duplicate `OrderedContest`s across different `OrderedHeader`s:
 
```
OrderedHeader 1
  OrderedContest a
    Contest x
  OrderedContest b
    Contest y
OrderedHeader 2
  OrderedContest c
    Contest z
  OrderedContest b
    Contest y
```

In this case, `Contest` y is duplicated. Do we remove the duplication and simply display `Contest`s x, y, z? Does this happen in practice, and is this something we need to have logic for?

More generally, is my assumption that we should "flatten" the contests accurate, or should we be doing something else here entirely?

## Question 2: what is the purpose of the `Header` class?

The `OrderedHeader` also contains a single `Header` class, which (per the documentation) "defines a reusable set of headers." It contains an `ExternalIdentifier` that "associates an ID with the ballot style". What does that mean?

It also includes a name.

What should we be doing with that information?

## Question 3: under what circumstances would a header not include contests?

Again, [the documentation](https://pages.nist.gov/ElectionResultsReporting/#18_5_3_43701b0_1527684342715_643544_6146) states the following (emphasis mine):

> OrderedContent is an abstract class with two subclasses that get used according to the type of content:
>
>*OrderedContest, used for the appearance of a contest. *OrderedHeader, used for the appearance of a header, **optionally with the inclusion of contests.**

This seems to suggest that an `OrderedHeader` may not contain contests. If that's the case, what would the ballot markup application present to the voter?

## Question 4: is it possible that an `OrderedContent` array would contain both `OrderedContest`s _and_ `OrderedHeader`s?

In theory, the spec allows for this. In practice, [example_1.json](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/example_1.json) and [example_2.json](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/example_2.json) have `OrderedContent` arrays that only either `OrderedContest`s OR `OrderedHeader`s - not a mix of both.

What does this look like in the real world? How would the ballot markup application display such a scenario?

**Comment by trustthevote** [comment]
Question 1, possibility two. Like
Header: "Federal Contests"
Contest: Senstor
Contest: House of Reps, 12th district
Header "State Contests"
Contest Governor

Question 2: What should we be doing with these headers?
For presenting ballot items, nothing. Paper ballots require these labels as separators between different kinds of contests. Screen ballots typically don't use a screen to say "now switching to state contests".
However, preview screens and review screens do sometimes use them.
We're waiting for a complete integrated app to address the usability and accessibility questions of these labels.

Questions 3 and 4: this is really more about the "profile" of conventional use of this data model, that we adopt in ElectOS. The schema lets you do a bunch of things in the name of flexibility, that aren't all that useful in practice.
We should articulate a set of constraints that will be respected by ElectOS components, like: don't produce headers with no contests in them. Or: it is possible to have headers with no contests in them because some print ballot layout requires them for compliance, but a screen ballot can ignore them.

**Comment by cwulfman** [comment]
I will defer to @trustthevote and/or John Dziurlaj (they wrote the spec, after all), but here are my thoughts.
### Question 1
**The answer is possibility 1.** The naming of the elements is certainly confusing (heck: the name _ballotstyle_ is confusing), but I think the intention is to support arbitrary nesting of sections of a ballot. It is, I think, just like the structuring of <div> elements in HTML 5:

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
    </head>
    <body>
        <div class="OrderedHeader">
            <header></header>
            <div class="OrderedContest">
                <div class="Contest">
                    <!-- the contest selections -->
                </div>
            </div>
        </div>
    </body>
</html>
```
### Question 2
NIST-1500-103 was designed to make as much content reusable as possible, to avoid duplication (and consequent bulking-up of records). It therefore tries to use the ID/IDREF relationship in XML, something like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<edf>
    <headers>
        <header id="state-contests-header">
            <name>State Contests</name>
        </header>
        <header id="orbit-city-contests-header">
            <name>Contests Specific to Orbit City Precinct</name>
        </header>
        <header id="spaceport-contests-header">
            <name>Contests Specific to Spaceport Precinct</name>
        </header>
        <!-- etc.,for all districts in the document -->
        <header id="executive-contests-header">
            <name>Contests for Executive Offices</name>
        </header>
        <header id="legislative-contests-header">
            <name>Contests for Legislative Offices</name>
        </header>
    </headers>
    <div class="OrderedHeader" header="state-contest-header">
        <div class="OrderedHeader" header="executive-contests-header">
            <div class="OrderedContest">
                <div class="ContestSelection"/>
                <div class="ContestSelection"/>
                <div class="ContestSelection"/>
            </div>
        </div>
        <div class="OrderedHeader" header="legislative-contests-header">
            <div class="OrderedContest">
                <div class="ContestSelection"/>
                <div class="ContestSelection"/>
                <div class="ContestSelection"/>
            </div>            
        </div>
    </div>
</edf>
```

**Comment by mattbeattie** [comment]
Thank you both! This helps tremendously. Let me summarize to make sure I understand everything correctly.

## Question 1: do `OrderedHeader`s contain `OrderedContent`s (per the documentation) or `OrderedContest`s (per the examples)?

John, your answer is "possibility two," which makes sense to me given your example.

Cliff, your answer is "possibility one;" however your example here supports "possibility two." Your [`example_2.json`](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/example_2.json) also suggests "possibility two." 

I'm going to code to "possibility two."

## Question 2: how do we display `OrderedHeader`s?

Based on John's written explanation and Cliff's HTML example, it sounds like the best way to handle this visually is to simply disregard the headers and only display the contests. 

## Questions 3 and 4: what about edge cases?

Given the answers to 1 and 2, I'm confident that I can write some parsing logic which will handle both subclasses of `OrderedContent` in a way that handles all edge cases. 

At the end of the day, all we're presenting to the voter is an array of contests.

**Comment by mattbeattie** [comment]
Will go ahead and close this issue since I have a path forward, feel free to re-open if this topic needs any additional clarification.

**Comment by cwulfman** [comment]
You-all should do whatever you want, but the [example2.json](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/example_2.json) file was generated from [example2.xml](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/example_2.xml), which conforms with possibility 1, not possibility 2.

> At the end of the day, all we're presenting to the voter is an array of contests.
I don't think this is correct; you are presenting a tree, not an array, like an outline.  Having said that, though, I realize there are two schools of thought wrt outlines: some, like me, say an outline is a tree with one section/container at the top; others say this is unnecessary.  And I suppose that latter model has won in the Word Processor World, so it's really whatever you want, I suppose.

**Comment by mattbeattie** [comment]
Apologies - didn't mean to close the issue without getting to a consensus. It sounds like this needs more discussion before we implement this in code.

## First, on possibility 1 (`OrderedHeader`s contain `OrderedContent`s) vs possibility 2 (`OrderedHeaders` contain `OrderedContest`s)

Cliff - your last message caused it to click for me. Given that `OrderedHeader`'s `OrderedContent` property is an abstract class, its value can be either `OrderedHeader` or `OrderedContest`.

_So possibility 1 and 2 are actually the same._

In practice though, a `BallotStyle`'s top-level `OrderedContent` array might contain `OrderedHeader`s, but those `OrderedHeader`s would contain an `OrderedContent` array that would only ever have `OrderedContest`s as the values in the array. Correct?

To prove this, let's consider the alternative. While it's _technically_  possible that a `BallotStyle`'s top-level `OrderedContent` array might contain `OrderedHeader`s that contain an `OrderedContent` array that contains `OrderedHeader`s as values in the array... that would never actually in practice. Right?

So what we're looking at _is_ the example that John gave us earlier, which I've indented to show the tree that Cliff mentioned:

```
Header: "Federal Contests"
  Contest: Senstor
  Contest: House of Reps, 12th district
Header "State Contests"
  Contest Governor
```

### Second, on how the data is displayed to the voter.

Cliff, I definitely agree that the data representation is more like a tree. There's a hierarchy in the EDF model when headers are concerned.

However, I don't know how that tree structure translates to the ballot presentation layer.

What I've seen from Elroy is that the voter is presented with an array of contests, and progresses through them linearly. There is no hierarchy or tree representation there.

I think what would help me is an understanding of what we SHOULD be presenting to the voter in practice. For example 2, what should the ballot look like?

**Comment by cwulfman** [comment]
>In practice though, a BallotStyle's top-level OrderedContent array might contain OrderedHeaders, but those OrderedHeaders would contain an OrderedContent array that would only ever have OrderedContests as the values in the array. Correct?

I think we'd have to survey Ballot Styles in the wild before we said that.  Ballot layouts, as I understand it, can be whatever the election officials want them to be, so someone could design a highly structured ballot for an election with lots and lots of contests.  That's all hypothetical, though, so unless the domain experts say otherwise I think you could probably assume a two-level tree.

So I agree with you: some more, and more realistic, mock-ups of ballot styles we need to support are definitely needed, though not, perhaps, for the March deadlines.

**Comment by mattbeattie** [comment]
I've added preliminary support for OrderedHeaders. I'll go ahead and close this; we can open a new issue later on if we need to revisit changes to the parsing logic.
