### ISSUE TITLE
Request: example CVR in JSON format

### ISSUE THREAD

**Issue by mattbeattie** [TrustTheVote-Project/NIST-1500-100-103-examples#37]
The NIST 2.0 EDF JSON examples ([1](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/example_1.json) and [2](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/example_2.json)) were incredibly helpful when creating the TypeScript model and associated parsing logic.

I would like to request a sample CVR in JSON format, so that I can create the corresponding TypeScript model and associated generation logic. The [documentation](https://pages.nist.gov/VoterRecordsInterchange/) is helpful, but seeing an example would be much more useful.

Is this something you can create an add to the repo?

**Comment by trustthevote** [comment]
its already an action for @cwulfman to add CVR examples for each EDF example.

**Comment by cwulfman** [comment]
>I would like to request a sample CVR in JSON format, so that I can create the corresponding TypeScript model and associated generation logic. The [documentation](https://pages.nist.gov/VoterRecordsInterchange/) is helpful, but seeing an example would be much more useful.

The documentation for the CastVoteRecord is [here](https://pages.nist.gov/CastVoteRecords/)

**Comment by cwulfman** [comment]
John Dziurlaj has an json example here: https://github.com/HiltonRoscoe/CDFPrototype/blob/master/CVR/json/example_2.json

In fact, https://github.com/HiltonRoscoe/CDFPrototype is chock-full of interesting stuff for us.

**Comment by mattbeattie** [comment]
Oh excellent. I should be able to programmatically create a CVR that looks like that based on the EDF and the voter's selections.

You weren't kidding - the [EXAMPLES.md](https://github.com/HiltonRoscoe/CDFPrototype/blob/master/CVR/EXAMPLES.md) in that repo has a ton of info.

One potential concern: the [version is 1.0.0](https://github.com/HiltonRoscoe/CDFPrototype/blob/master/CVR/json/example_2.json#L417) - do you know if this corresponds to NIST 1.0? Is 1.0 vs 2.0 a thing for CVRs too, or just EDFs?

**Comment by cwulfman** [comment]
I think there is only one version of NIST-1500-103

**Comment by mattbeattie** [comment]
Perfect, this should be all I need to get started then. Thanks so much!
