### ISSUE TITLE
Update test_cases/example_1.json  and example_2.json to conform with jetsons_election_definition.json

### ISSUE THREAD

**Issue by cwulfman** [TrustTheVote-Project/NIST-1500-100-103-examples#45]
`jetsons_election_definition.json` is an example of an "election-definition file" in a particular sense: it contains all the election data for all the precincts. Examples 1 and 2 are meant to be examples of precinct-level EDFs, of the kind the Provisioner would send to the Markit app.

We have been refining the `jetsons_election_definition.json` file; the derivatives need now to be refined as well.  (All this hand-work is in the service of creating a mockup; most of this work should be automated.)

**Comment by awoflaherty** [comment]
@cwulfman Attached is the correct representation of example 2 you are working on?

![Jetson Precint Map](https://user-images.githubusercontent.com/3749789/168680501-86539b86-87de-4e13-8fa2-c93672455fc7.png)

**Comment by cwulfman** [comment]
There's a finished map in the repository: https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/Gadget_County.svg
