### ISSUE TITLE
Implement a hook for creating a unique id for a mark in the PDF.

### ISSUE THREAD

**Issue by cwulfman** [TrustTheVote-Project/NIST-1500-100-103-examples#47]

**Comment by cwulfman** [comment]
Motivation: PDF generator must be able to associate a choice from the EDF with something in the PDF, so that a choice made in the Markit UI can be recorded on the PDF (which is the source of truth).

The internal composition of the ballot PDF has yet to be determined.  It appears, however, that interactive form elements (i.e., radio buttons) cannot be used, because the widget set Adobe provides for radio buttons does not include a shape that matches the required oval on a ballot.

The EDF is, at this point, the intermediary between the Markit form and the PDF.

The relevant element in NIST-1500-100 is ContestSelection (or, specifically, ContestSelection's subtypes CandidateSelection and BallotMeasureSelection). While NIST-1500-100 provides  an ExternalIdentifier sub-element which might be used, the schema **does not** allow ExternalIdentifier to appear within a ContestSelection.

Why not use the id of the ContestSelection?

Also to consider: shouldn't Markit be generating a CVR as its output? Expressing the contents of the CVR on a PDF ballot is a separate operation.

**Comment by trustthevote** [comment]
Yes, the contest selection's id should be field to use. It should have a human friendly naming convention (so that CVRs have some degree of human comprehensibility) but since we can count in uniqueness, there would need to be a suffix that is unique -- not globally, just unique within one election-def dataset. As a result it could just a string rep of an integer counter.

**Comment by cwulfman** [comment]
Here's a fragment of the current EDF:

```json
                {
                    "OfficeIds": ["office_mayor"],
                    "VotesAllowed": 1,
                    "@type": "ElectionResults.CandidateContest",
                    "@id": "contest-orbit-city-mayor",
                    "ContestSelection": [
                        {
                            "CandidateIds": ["candidate_spacely"],
                            "@type": "ElectionResults.CandidateSelection",
                            "@id": "selection_spacely",
                            "SequenceOrder": 1
                        },
```
What if the convention were to be SelectionId = ContestId + CandidateId?  E.g.,

```json
                {
                    "OfficeIds": ["office_mayor"],
                    "VotesAllowed": 1,
                    "@type": "ElectionResults.CandidateContest",
                    "@id": "contest_orbit-city-mayor",
                    "ContestSelection": [
                        {
                            "CandidateIds": ["candidate_spacely"],
                            "@type": "ElectionResults.CandidateSelection",
                            "@id": "contest_orbit-city-mayor__candidate_spacely",
                            "SequenceOrder": 1
                        },
```
To be compatible with XML, @ids must be NCNames (https://www.w3.org/TR/xml-names11/#NT-NCName)
