### ISSUE TITLE
Feedback on example_2.json:

### ISSUE THREAD

**Issue by awoflaherty** [TrustTheVote-Project/NIST-1500-100-103-examples#48]
https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/example_2.json

My focus is on the text (Content) informations.
1. Most Content in Precinct area is capitalized except #L181 and #L196
2. Mayor of Orbit City has a period(.) at the end on #L231
3. Candidate Smith is lower case on lone #L496
4. I am concerned about the "\n" in some of the ballot text such as on #L1069.  With a narrow device screen, forcing an enter line in a paragraph may not look good.

**Comment by cwulfman** [comment]
Anne, you had requested a way to signal paragraph breaks; the "\n" characters in the long texts are, in fact, paragraph breaks and not line breaks (at least they are intended to function that way). Real input, especially in "long ballot measures", may well have paragraph breaks, unless we explicitly disallow them.

That said, if you still want them removed, I can remove them.

**Comment by cwulfman** [comment]
Some quick notes on the example2 I am reading:

126: spaceport district is not a city, need to use another type, possible "other"

229/243: the text object appears twice in this office, but only once in the others. some dupes to remove?

317: name should be "Leptonican"

335: name should be "Hadronicrat"

348: good to see a person object for Jane but I think also needed a persons for the other candidates in the spaceport board election and school board election

900's contests generally - what is indication for partisan vs. non partisan?

1059: con statement pro statement and summary are not part of ballots, could be omitted in our profile.

1069: fulltext content -- note open question to Anne if long enough

1265: should be "President of the United States"

EJS

**Comment by cwulfman** [comment]
is_partisan default is true (spec, p. 61):

>Boolean to indicate whether the office is partisan, e.g., true or false. If not present, assumption is true.

**Comment by cwulfman** [comment]
Anne says length of fulltext is sufficient.

**Comment by cwulfman** [comment]
> 348: good to see a person object for Jane but I think also needed a persons for the other candidates in the spaceport board election and school board election

We had a person object for Jane because she had no party affiliation and Matt wanted to be able to grab her profession.  I'll add the others for completness' sake, though.
