### ISSUE TITLE
We need to determine how to parse and display ballot styles with nested headers

### ISSUE THREAD

**Issue by mattbeattie** [TrustTheVote-Project/NIST-1500-100-103-examples#52]
I pulled the new [edf_downtown-precinct.json](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/blob/main/test_cases/edf_downtown-precinct.json) EDF and am having some trouble parsing it. This EDF's ballot style contains nested headers, and my current parsing logic doesn't know how to handle that.

Below I've explained the issue in detail, and have outlined a few possible paths forward. We should probably talk about how best to handle this case, because we'll definitely need to handle it in the wild.

# High-level overview

In technical terms, the issue is with the `BallotStyle`'s `OrderedContent` array, which contains a single `OrderedHeader`. That `OrderedHeader` has an `OrderedContent` array that contains two objects. Both objects are `OrderedHeader`s whose `OrderedContent` arrays contains a single `OrderedContest`.

In _simpler_ terms, the ballot style contains nested headers. I never accounted for this case my original parsing logic, and I'm admittedly not sure how to handle it. I'm not even sure what such a paper ballot would look like, and so I'm not sure how to represent it in Markit.

For the full context, let's revisit the GitHub issue we had a few months ago about this topic: https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/issues/35

In that issue, I wrote the following:

> In practice though, a `BallotStyle`'s top-level `OrderedContent` array might contain `OrderedHeader`s, but those `OrderedHeader`s would contain an `OrderedContent` array that would only ever have `OrderedContest`s as the values in the array. Correct?
> 
> To prove this, let's consider the alternative. While it's _technically_  possible that a `BallotStyle`'s top-level `OrderedContent` array might contain `OrderedHeader`s that contain an `OrderedContent` array that contains `OrderedHeader`s as values in the array... that would never actually in practice. Right?

The example we gave in the GitHub issue was the following:

```
Header: "Federal Contests"
  Contest: Senstor
  Contest: House of Reps, 12th district
Header "State Contests"
  Contest Governor
```

What we have here in this EDF is something like this:

```
Header: Orbit City Contests
  Header: <no match found for Header_Office_Mayor__GpUnit_Orbit-City>
    Contest: Contest for Mayor of Orbit City
  Header: <no match found for Header_County-Gadget>
    Contest: Air Traffic Control Tax Increase
```

So there's two issues here:

1. There's no match for two of the header IDs
2. My parsing logic doesn't know how to handle headers which contain headers

In the next section, I'm going to focus on the second one, because the first one should be easy to solve.

# Identifying a path forward

In the original GitHub issue, I suggested the following resolution:

> I definitely agree that the data representation is more like a tree. There's a hierarchy in the EDF model when headers are concerned.
> 
> However, I don't know how that tree structure translates to the ballot presentation layer.
> 
> What I've seen from Elroy is that the voter is presented with an array of contests, and progresses through them linearly. There is no hierarchy or tree representation there.

And that's what I built in my first iteration. I assumed that headers will only have contests, and I simply flatten that structure to an array of contests. I pretty much throw away anything related to headers, because they are not represented in Elroy in any fashion at this time.

@cwulfman, the predictions you made were spot on:

> I think we'd have to survey Ballot Styles in the wild before we said that. Ballot layouts, as I understand it, can be whatever the election officials want them to be, so someone could design a highly structured ballot for an election with lots and lots of contests. That's all hypothetical, though, so unless the domain experts say otherwise I think you could probably assume a two-level tree.
> 
> So I agree with you: some more, and more realistic, mock-ups of ballot styles we need to support are definitely needed, though not, perhaps, for the March deadlines.

We are now past March, and ready to open up this conversation again :)

For the sake of next steps, I think we have a few options going forward. I've listed them below in increasing difficulty.

1. I can update my logic to handle infinitely nested headers, and will simply grab all the contests and display them serially to the voter
2. Willfully take headers into account when parsing the EDF, and display "something" for them in the ballot markup section of Markit (while still presenting the contests serially)
3. Build the hierarchy model into Markit (I'm not sure what this looks like)

I can definitely accomplish 1 on my own in a reasonable amount of time. If we need to revisit the content displayed to the voter (2) or consider introducing hierarchy (3), then we'll need a more in-depth conversation here.

**Comment by cwulfman** [comment]
>So there's two issues here:
>
>    There's no match for two of the header IDs
>   My parsing logic doesn't know how to handle headers which contain headers
>
>In the next section, I'm going to focus on the second one, because the first one should be easy to solve.

I've fixed two mistakes in the EDF (https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/commit/91095b703578f54c714625c57d1393f028642025 and https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/commit/c7858c3c7aee5c808a27da95dabc5b18cf8306e8).  Thanks for spotting these!

**Comment by cwulfman** [comment]
With respect to the next steps you outline above, I think there are two stages to consider.

1. In the immediate term, your team is working against a rapidly approaching deadline, and I think you should feel free to amend these test cases as you see fit to make them comply with the logic you have at this point. I suggest you create a test directory in your repo (you may already have done this) and manage your own versions of the EDFs  you're working with.  No need to consult with me or to keep track of the changes I'm making to the examples as the profile evolves.
2. In the longer term, you will, of course, need to be involved in the development of the profile, since Elroy is a principal consumer of the EDFs.  The fact, however, that Elroy is at this point the _only_ consumer of EDFs should not lull us into designing the election definition profile (particularly the BallotStyle element) simply to support presenting choices on a mobile device.  We can make the profile whatever we like, but we should be judicious in what we disallow.

**Comment by mattbeattie** [comment]
Thanks for the fixes! It looks like that flattened the structure, so it's something my parser is able to handle. Long term though, of course, we'll want the ability to handle (or at least be aware of) nested hierarchy. Good to know we can push that to a later time.

Agree on maintaining our own versions of the EDFs. We do already do that, but I like to stay up to date (and pull in new ones when I can) to make sure our parser can handle as many edge cases as possible.

**Comment by mattbeattie** [comment]
@cwulfman one last comment on this one: I had to add a vote variation of plurality to the candidate contest in order for it to work. I opened a PR here to affect that change at the source: https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/pull/53

**Comment by cwulfman** [comment]
@mattbeattie we've discussed this in this evening's meeting and made changes.  Can we close this issue?

**Comment by mattbeattie** [comment]
Definitely! Thanks for all the help on this topic.
