### ISSUE TITLE
The OfficeIds for the Presidential race should include the VP office

### ISSUE THREAD

**Issue by cwulfman** [TrustTheVote-Project/NIST-1500-100-103-examples#63]

**Comment by cwulfman** [comment]
Here is the definition as it currently appears in the August test file:

```json
{
                    "@type": "ElectionResults.CandidateContest",
                    "@id": "recsoZy7vYhS3lbcK",
                    "Name": "President of the United States",
                    "ExternalIdentifier": [
                        {
                            "@type": "ElectionResults.ExternalIdentifier",
                            "Type": "other",
                            "OtherType": "https://viaf.org/viaf/",
                            "Value": "129529146"
                        }
                    ],
                    "OfficeIds": ["recFr8nr6uAZsD2r8"],
                    "VoteVariation": "plurality",
                    "VotesAllowed": 1,
                    "ElectionDistrictId": "recTXCMIfa5VQJju2",
                    "ContestSelection": [
                        {
                            "@type": "ElectionResults.CandidateSelection",
                            "@id": "recQK3J9IJq42hz2n",
                            "CandidateIds": [
                                "reczKIKk81RshXkd9",
                                "recLB4X1sLL2q1bSW"
                            ]
                        },
                        {
                            "@type": "ElectionResults.CandidateSelection",
                            "@id": "reccUkUdEznfODgeL",
                            "CandidateIds": [
                                "recopGzcpflkyhwdN",
                                "recBEqMDC9w5AnKxh"
                            ]
                        },
                        {
                            "@type": "ElectionResults.CandidateSelection",
                            "@id": "recPod2L8VhwagiDl",
                            "IsWriteIn": true
                        }
                    ]
                },
```

the `OfficeIds` property of a `CandidateContest` can have [0..*]values, so it seems perfectly reasonable to include the OfficeId for VPOTUS in the list.  However, a case could be made that neither the POTUS nor the VPOTUS OfficeIds should be associated with this contest, because neither is being elected directly: the voter is voting for an unnamed elector (or slate of electors).  See, for example, https://www.post-gazette.com/news/politics-local/2020/10/14/Election-ballots-mail-in-absentee-incorrect-allegheny-county-pittsburgh-voters/stories/202010140139

**Comment by stratofax** [comment]
@cwulfman can we either:

- Reopen this issue; or
- Open a discussion to identify the definitive way to count the number of candidates on the ticket

For example, if the OfficeIds property includes two (2) values, we know that the `CandidateContest` should list either two Candidates for each ticket and write in. Otherwise, how do we know that a sufficient number of candidates are listed for each ticket?

**Comment by cwulfman** [comment]
>Open a discussion to identify the definitive way to count the number of candidates on the ticket
That's a different, albeit related issue to the task of adding the VPOTUS id to test cases.  By all means let's open a discussion about that.

**Comment by stratofax** [comment]
OK, sounds good! Here? [ElectOS-Dev · The TrustTheVote® Project Discussions](https://github.com/orgs/TrustTheVote-Project/teams/electos-dev)

**Comment by stratofax** [comment]
In fact, I opened a discussion here: [EDFs and Ballot Layout · Discussion #27 · ion-oset/DAVS](https://github.com/ion-oset/DAVS/discussions/27)

**Comment by cwulfman** [comment]
Re-opening for further documentation, from the Spec (section 5.8, Class CandidateContest):
>... If the candidate contest is associated with a ticket (of candidates) and each candidate in the ticket is associated with a separate office, the association to Office can reference each of the separate offices. For example, if the contest is for the state governor ticket but Governor and Lieutenant (Lt.) Governor are both separate offices, the association references first to the Office instance defined for the Governor’s office and then to the Lt. Governor’s office. In this case, it is expected that the generating application will list the multiple references according to a jurisdiction-defined ordering scheme, e.g., Governor first and Lt. Governor second.

**Comment by stratofax** [comment]
@cwulfman I'm not clear what decision we reached on this issue, but I do think that whatever it is, you should record it in [ballot_layout_considerations · TrustTheVote-Project/NIST-1500-100-103-examples Wiki](https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/wiki/ballot_layout_considerations).

In general, I think recording the decision to the **Ballot Layout Considerations** doc is the way to resolve and close these kind of issues in the future.

**Comment by cwulfman** [comment]
The short answer is yes;  see https://github.com/TrustTheVote-Project/NIST-1500-100-103-examples/issues/63#issuecomment-1237259255, above:

>If the candidate contest is associated with a ticket (of candidates) and each candidate in the ticket is associated with a separate office, the association to Office can reference each of the separate offices.
